---
# tasks file for ansible-role-wireshark

- name: run apt-get update
  apt:
    update_cache: yes
  become: yes

- name: let non root to capture traffic
  # Before installing any package, this only sets the preference for the question
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'
  become: yes

- name: install cli package
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_cli_package }}"
  when: wireshark_cli
  become: yes

- name: install gui package
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_gui_package }}"
  when: wireshark_gui
  become: yes

- name: add current user to wireshark group
  user:
    name: "{{ wireshark_user }}"
    append: yes
    groups: wireshark
  become: yes
